name: dirish-tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dotnet build and publish
        run: |         
          cat ${secrets.DIRISH} > test.txt
          cat test.txt
