name: dirish-tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: shebzul
        env:
          ALNI: ${{ secrets.SHEBZUL }}
        run: |
          mkdir myapp
          touch testfile
          echo $ALNI >> myapp/testfile
          ls -l
          cat testfile         
             
      - name: shebzul
        env:
          TEPESI: ${{ secrets.DIRISH }}
        run: |
          mkdir myapp
          touch base64file
          echo $TEPESI >> myapp/base64file         
          cat myapp/base64file | base64 --decode > myapp/adambalasifile
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: shebi
          path: ./myapp

        

